apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
        - name: hello-openshift
          image: openshift/hello-openshift:latest
          ports:
            - containerPort: 80

        - name: kafka
          image: bitnami/kafka
          ports:
            - containerPort: 90